services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: ${DOCKER_BACKEND_IMAGE:-songhee2/e2e-keypad-project:backend-v1}
    environment:
      SERVER_PORT: ${BACKEND_PORT:-8080}
      BANK_SERVER_URL: ${BANK_SERVER_URL:-http://bank:8081}
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    depends_on:
      - bank
    networks:
      - app-net

  bank:
    build:
      context: .
      dockerfile: Dockerfile.bank
    image: ${DOCKER_BANK_IMAGE:-songhee2/e2e-keypad-project:bank-v1}
    environment:
      BANK_SERVER_PORT: ${BANK_PORT:-8081}
    ports:
      - "${BANK_PORT:-8081}:8081"
    networks:
      - app-net

  frontend:
    build:
      context: ./src/main/websrc
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-http://backend:8080}
    image: ${DOCKER_FRONTEND_IMAGE:-songhee2/e2e-keypad-project:frontend-v1}
    environment:
      PORT: ${FRONTEND_PORT:-3000}
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-http://backend:8080}
      NEXT_PUBLIC_BANK_API_URL: ${NEXT_PUBLIC_BANK_API_URL:-http://bank:8081}
    depends_on:
      - backend
      - bank
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
